/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type AudioFile = {
	asset?: SanityFileAssetReference;
	media?: unknown; // Unable to locate the referenced type "audioFile.media" in schema
	_type: 'file';
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type HostAvatar = {
	asset?: SanityImageAssetReference;
	media?: unknown; // Unable to locate the referenced type "hostAvatar.media" in schema
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	_type: 'image';
};

export type StoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'story';
};

export type RotatingContent = {
	_id: string;
	_type: 'rotatingContent';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	mostRead?: Array<
		{
			_key: string;
		} & StoryReference
	>;
};

export type Tag = {
	_id: string;
	_type: 'tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description: string;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type AuthorReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'author';
};

export type ResourceTypeReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'resourceType';
};

export type TagReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'tag';
};

export type LiteraryWork = {
	_id: string;
	_type: 'literaryWork';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	authors: Array<
		{
			_key: string;
		} & AuthorReference
	>;
	coverImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	content: Array<{
		title?: string;
		epigraphs?: Array<{
			text?: Markdown;
			reference?: Markdown;
			_type: 'epigraph';
			_key: string;
		}>;
		body: Markdown;
		readingTime?: number;
		_type: 'section';
		_key: string;
	}>;
	editorialNote?: Markdown;
	totalReadingTime?: number;
	mediaSources?: Array<
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'audioRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				audioFile: AudioFile;
				hostName: string;
				hostAvatar?: HostAvatar;
				date: string;
				duration: string;
				_type: 'spaceRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				videoId: string;
				_type: 'youTubeVideo';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'spotifyPodcastEpisode';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'pdfLink';
				_key: string;
		  }
	>;
	resources?: Array<{
		title: string;
		url: string;
		resourceType: ResourceTypeReference;
		_type: 'resource';
		_key: string;
	}>;
	badLanguage?: boolean;
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
	originalPublication?: string;
	publishedAt?: string;
};

export type Markdown = string;

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type Story = {
	_id: string;
	_type: 'story';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	author: AuthorReference;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	mediaSources?: Array<
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'audioRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				audioFile: AudioFile;
				hostName: string;
				hostAvatar?: HostAvatar;
				date: string;
				duration: string;
				_type: 'spaceRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				videoId: string;
				_type: 'youTubeVideo';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'spotifyPodcastEpisode';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'pdfLink';
				_key: string;
		  }
	>;
	resources?: Array<{
		title: string;
		url: string;
		resourceType: ResourceTypeReference;
		_type: 'resource';
		_key: string;
	}>;
	badLanguage: boolean;
	approximateReadingTime: ComputedNumber;
	epigraphs?: Array<{
		text: BlockContent;
		reference?: BlockContent;
		_type: 'epigraph';
		_key: string;
	}>;
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
	body?: BlockContent;
	review?: BlockContent;
	originalPublication: string;
	publishedAt?: string;
};

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
			listItem?: 'bullet' | 'number';
			markDefs?: Array<{
				href?: string;
				_type: 'link';
				_key: string;
			}>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
			_key: string;
	  }
>;

export type ComputedNumber = number;

export type NationalityReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'nationality';
};

export type Author = {
	_id: string;
	_type: 'author';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	nationality: NationalityReference;
	bornOn?: string;
	bornOnYear?: ComputedNumber;
	diedOn?: string;
	diedOnYear?: ComputedNumber;
	biography: Markdown;
	resources?: Array<{
		title: string;
		url: string;
		resourceType: ResourceTypeReference;
		_type: 'resource';
		_key: string;
	}>;
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
};

export type Nationality = {
	_id: string;
	_type: 'nationality';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	country: string;
	flag: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type LiteraryWorkReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'literaryWork';
};

export type Collection = {
	_id: string;
	_type: 'collection';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description: Markdown;
	featuredImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
	config?: {
		showAuthors?: boolean;
	};
	literaryWorks?: Array<
		{
			_key: string;
		} & LiteraryWorkReference
	>;
	mediaSources?: Array<
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'audioRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				audioFile: AudioFile;
				hostName: string;
				hostAvatar?: HostAvatar;
				date: string;
				duration: string;
				_type: 'spaceRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				videoId: string;
				_type: 'youTubeVideo';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'spotifyPodcastEpisode';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'pdfLink';
				_key: string;
		  }
	>;
};

export type Storylist = {
	_id: string;
	_type: 'storylist';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description: BlockContent;
	featuredImage?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
	config?: {
		showAuthors?: boolean;
	};
	stories?: Array<
		{
			_key: string;
		} & StoryReference
	>;
	tabs?: Array<{
		title: string;
		slug: Slug;
		content: BlockContent;
		icon?: string;
		_type: 'storylistTab';
		_key: string;
	}>;
	mediaSources?: Array<
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'audioRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				audioFile: AudioFile;
				hostName: string;
				hostAvatar?: HostAvatar;
				date: string;
				duration: string;
				_type: 'spaceRecording';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				videoId: string;
				_type: 'youTubeVideo';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'spotifyPodcastEpisode';
				_key: string;
		  }
		| {
				title: string;
				description: Markdown;
				url: string;
				_type: 'pdfLink';
				_key: string;
		  }
	>;
};

export type ContentCampaign = {
	_id: string;
	_type: 'contentCampaign';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	url?: string;
	contents?: {
		xs?: {
			image?: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		md?: {
			image?: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
	};
};

export type ContentCampaignReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'contentCampaign';
};

export type StorylistReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'storylist';
};

export type LandingPage = {
	_id: string;
	_type: 'landingPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	config: string;
	slug: Slug;
	campaigns?: Array<
		{
			_key: string;
		} & ContentCampaignReference
	>;
	cards?: Array<
		{
			_key: string;
		} & StorylistReference
	>;
	latestReads?: Array<
		{
			_key: string;
		} & StoryReference
	>;
};

export type Resource = {
	_type: 'resource';
	title: string;
	url: string;
	resourceType: ResourceTypeReference;
};

export type ResourceType = {
	_id: string;
	_type: 'resourceType';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description: string;
};

export type Contributor = {
	_id: string;
	_type: 'contributor';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
	area: 'staff' | 'programming' | 'content-generation' | 'content-pick';
	link?: {
		handle?: string;
		url?: string;
	};
	notes?: string;
};

export type ComputedText = string;

export type ComputedString = string;

export type ComputedBoolean = boolean;

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SanityFileAssetReference
	| AudioFile
	| SanityImageAssetReference
	| HostAvatar
	| StoryReference
	| RotatingContent
	| Tag
	| Slug
	| AuthorReference
	| ResourceTypeReference
	| TagReference
	| LiteraryWork
	| Markdown
	| SanityImageCrop
	| SanityImageHotspot
	| Story
	| BlockContent
	| ComputedNumber
	| NationalityReference
	| Author
	| Nationality
	| LiteraryWorkReference
	| Collection
	| Storylist
	| ContentCampaign
	| ContentCampaignReference
	| StorylistReference
	| LandingPage
	| Resource
	| ResourceType
	| Contributor
	| ComputedText
	| ComputedString
	| ComputedBoolean
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: ../src/api/_queries/author.query.ts
// Variable: authorBySlugQuery
// Query: *[_type == 'author' && slug.current == $slug && !(_id in path('drafts.**'))][0]{    _id,    'slug': slug.current,    'createdAt': _createdAt,    'updatedAt': _updatedAt,    name,    image,    nationality->,    biography,    bornOn,		bornOnYear,    diedOn,		diedOnYear,    'resources': coalesce(resources[]{        title,        url,        resourceType->{        	'slug': slug.current,        	title,        	description        }    }, []),    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, [])}
export type AuthorBySlugQueryResult = {
	_id: string;
	slug: string;
	createdAt: string;
	updatedAt: string;
	name: string;
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	nationality: {
		_id: string;
		_type: 'nationality';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		country: string;
		flag: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	biography: Markdown;
	bornOn: string | null;
	bornOnYear: ComputedNumber | null;
	diedOn: string | null;
	diedOnYear: ComputedNumber | null;
	resources:
		| Array<{
				title: string;
				url: string;
				resourceType: {
					slug: string;
					title: string;
					description: string;
				};
		  }>
		| Array<never>;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
} | null;

// Source: ../src/api/_queries/author.query.ts
// Variable: authorsQuery
// Query: *[_type == 'author' && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    name,    image,    nationality->,    bornOn, 		bornOnYear,    diedOn,    diedOnYear,    'resources': []}|order(name asc)
export type AuthorsQueryResult = Array<{
	_id: string;
	slug: string;
	name: string;
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	nationality: {
		_id: string;
		_type: 'nationality';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		country: string;
		flag: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
	};
	bornOn: string | null;
	bornOnYear: ComputedNumber | null;
	diedOn: string | null;
	diedOnYear: ComputedNumber | null;
	resources: Array<never>;
}>;

// Source: ../src/api/_queries/collection.query.ts
// Variable: collectionBySlugQuery
// Query: *[_type == 'collection' && slug.current == $slug && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,    description,    featuredImage,    'config': { 'showAuthors': coalesce(config.showAuthors, false) },    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'mediaSources': coalesce(mediaSources[]{        ...,        _type == 'spaceRecording' => {            'audioUrl': audioFile.asset->url        }    }, []),    'literaryWorks': coalesce(literaryWorks[]->{        _id,        'slug': slug.current,        title,        coverImage,        totalReadingTime,        'sectionCount': count(content),        'tags': coalesce(tags[] -> {            title,            'slug': slug.current,            description        }, []),        'mediaSources': coalesce(mediaSources[]{            ...,            _type == 'spaceRecording' => {                'audioUrl': audioFile.asset->url            }        }, []),        'authors': coalesce(authors[]->{            _id,            'slug': slug.current,            name,            image,            nationality->,            bornOn,            bornOnYear,            diedOn,            diedOnYear        }, []),        'teaserSection': content[0...1]{            _key,            title,            body,            readingTime        }    }, [])}[0]
export type CollectionBySlugQueryResult = {
	_id: string;
	slug: string;
	title: string;
	description: Markdown;
	featuredImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	config: {
		showAuthors: boolean | false;
	};
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	literaryWorks:
		| Array<{
				_id: string;
				slug: string;
				title: string;
				coverImage: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
				totalReadingTime: number | null;
				sectionCount: number;
				tags:
					| Array<{
							title: string;
							slug: string;
							description: string;
					  }>
					| Array<never>;
				mediaSources:
					| Array<never>
					| Array<
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'audioRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'pdfLink';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									audioFile: AudioFile;
									hostName: string;
									hostAvatar?: HostAvatar;
									date: string;
									duration: string;
									_type: 'spaceRecording';
									_key: string;
									audioUrl: string | null;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'spotifyPodcastEpisode';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									videoId: string;
									_type: 'youTubeVideo';
									_key: string;
							  }
					  >;
				authors: Array<{
					_id: string;
					slug: string;
					name: string;
					image: {
						asset?: SanityImageAssetReference;
						media?: unknown;
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					};
					nationality: {
						_id: string;
						_type: 'nationality';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						country: string;
						flag: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						};
					};
					bornOn: string | null;
					bornOnYear: ComputedNumber | null;
					diedOn: string | null;
					diedOnYear: ComputedNumber | null;
				}>;
				teaserSection: Array<{
					_key: string;
					title: string | null;
					body: Markdown;
					readingTime: number | null;
				}>;
		  }>
		| Array<never>;
} | null;

// Source: ../src/api/_queries/collection.query.ts
// Variable: collectionsQuery
// Query: *[_type == 'collection' && !(_id in path('drafts.**'))]| order(title asc){    _id,    'slug': slug.current,    title,    description,    featuredImage,    'config': { 'showAuthors': coalesce(config.showAuthors, false) },    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'mediaSources': coalesce(mediaSources[]{        ...,        _type == 'spaceRecording' => {            'audioUrl': audioFile.asset->url        }    }, []),    'count': coalesce(count(literaryWorks), 0),    'literaryWorkCoverImages': coalesce(literaryWorks[0...3]->coverImage, [])}
export type CollectionsQueryResult = Array<{
	_id: string;
	slug: string;
	title: string;
	description: Markdown;
	featuredImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	config: {
		showAuthors: boolean | false;
	};
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	count: number | 0;
	literaryWorkCoverImages:
		| Array<never>
		| Array<{
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
		  } | null>;
}>;

// Source: ../src/api/_queries/content.query.ts
// Variable: rotatingContentQuery
// Query: *[_type == 'rotatingContent' && _id == 'rotatingContent'][0]{    _id,    name,    'mostRead': coalesce(mostRead[]->{        _id,        'slug': slug.current,        title,        'badLanguage': coalesce(badLanguage, false),        'body': [],        'originalPublication': coalesce(originalPublication, ''),        approximateReadingTime,        coverImage,        'resources': [],        'mediaSources': coalesce(mediaSources[], []),        'author': author-> {            _id,            'slug': slug.current,            name,            image,            nationality->,						bornOn,						bornOnYear,						diedOn,						diedOnYear,            'resources': [],        }    },[])}
export type RotatingContentQueryResult = {
	_id: 'rotatingContent';
	name: string;
	mostRead:
		| Array<{
				_id: string;
				slug: string;
				title: string;
				badLanguage: boolean;
				body: Array<never>;
				originalPublication: string;
				approximateReadingTime: ComputedNumber;
				coverImage: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				resources: Array<never>;
				mediaSources:
					| Array<never>
					| Array<
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'audioRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'pdfLink';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									audioFile: AudioFile;
									hostName: string;
									hostAvatar?: HostAvatar;
									date: string;
									duration: string;
									_type: 'spaceRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'spotifyPodcastEpisode';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									videoId: string;
									_type: 'youTubeVideo';
									_key: string;
							  }
					  >;
				author: {
					_id: string;
					slug: string;
					name: string;
					image: {
						asset?: SanityImageAssetReference;
						media?: unknown;
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					};
					nationality: {
						_id: string;
						_type: 'nationality';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						country: string;
						flag: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						};
					};
					bornOn: string | null;
					bornOnYear: ComputedNumber | null;
					diedOn: string | null;
					diedOnYear: ComputedNumber | null;
					resources: Array<never>;
				};
		  }>
		| Array<never>;
} | null;

// Source: ../src/api/_queries/content.query.ts
// Variable: landingPageListQuery
// Query: *[_type == 'landingPage' && !(_id in path('drafts.**')) && slug.current in $slugs]{		_id,		'slug': slug.current,		config,}
export type LandingPageListQueryResult = Array<{
	_id: string;
	slug: string;
	config: string;
}>;

// Source: ../src/api/_queries/content.query.ts
// Variable: latestLandingPageReferencesQuery
// Query: *[_type == 'landingPage' && !(_id in path('drafts.**')) && config <= $currentSlug]{    _id,    _type,    'slug': slug.current,    config,    'cards': coalesce(cards[],[]),    'campaigns': coalesce(campaigns[],[]),    'latestReads': coalesce(latestReads,[]),} | order(config desc, _createdAt desc)[0]
export type LatestLandingPageReferencesQueryResult = {
	_id: string;
	_type: 'landingPage';
	slug: string;
	config: string;
	cards:
		| Array<
				{
					_key: string;
				} & StorylistReference
		  >
		| Array<never>;
	campaigns:
		| Array<
				{
					_key: string;
				} & ContentCampaignReference
		  >
		| Array<never>;
	latestReads:
		| Array<
				{
					_key: string;
				} & StoryReference
		  >
		| Array<never>;
} | null;

// Source: ../src/api/_queries/content.query.ts
// Variable: landingPageContentQuery
// Query: *[_type == 'landingPage' && !(_id in path('drafts.**')) && slug.current == $slug][0]{    _id,    'slug': slug.current,    config,    'cards': coalesce(cards[]->{        _id,        title,        'slug': slug.current,        description,        featuredImage,        'tags': coalesce(tags[] -> {            title,            'slug': slug.current,            description        }, []),        'storyCoverImages': coalesce(stories[]->coverImage, []),        'count': coalesce(count(stories), 0),				config,				'tabs': [],	      'mediaSources': coalesce(mediaSources[], []),    },[]),    'campaigns': coalesce(campaigns[]->{        _id,        'title': coalesce(title, ''),        'slug': coalesce(slug.current, ''),        'url': coalesce(url, ''),        'contents': {            'xs': {                'image': contents.xs.image            },            'md': {                'image': contents.md.image            }        }    },[]),    'latestReads': coalesce(latestReads[]->{        _id,        'slug': slug.current,        title,        'badLanguage': coalesce(badLanguage, false),        'body': [],        'originalPublication': coalesce(originalPublication, ''),        approximateReadingTime,        coverImage,        'resources': [],        'mediaSources': coalesce(mediaSources[], []),        'author': author-> {             _id,            'slug': slug.current,            name,            image,            nationality->,						bornOn,						bornOnYear,						diedOn,						diedOnYear,            'resources': [],        }    },[]),}
export type LandingPageContentQueryResult = {
	_id: string;
	slug: string;
	config: string;
	cards:
		| Array<{
				_id: string;
				title: string;
				slug: string;
				description: BlockContent;
				featuredImage: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
				tags:
					| Array<{
							title: string;
							slug: string;
							description: string;
					  }>
					| Array<never>;
				storyCoverImages:
					| Array<{
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
					  }>
					| Array<never>;
				count: number | 0;
				config: {
					showAuthors?: boolean;
				} | null;
				tabs: Array<never>;
				mediaSources:
					| Array<never>
					| Array<
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'audioRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'pdfLink';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									audioFile: AudioFile;
									hostName: string;
									hostAvatar?: HostAvatar;
									date: string;
									duration: string;
									_type: 'spaceRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'spotifyPodcastEpisode';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									videoId: string;
									_type: 'youTubeVideo';
									_key: string;
							  }
					  >;
		  }>
		| Array<never>;
	campaigns:
		| Array<{
				_id: string;
				title: string | '';
				slug: string | '';
				url: string | '';
				contents: {
					xs: {
						image: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						} | null;
					};
					md: {
						image: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						} | null;
					};
				};
		  }>
		| Array<never>;
	latestReads:
		| Array<{
				_id: string;
				slug: string;
				title: string;
				badLanguage: boolean;
				body: Array<never>;
				originalPublication: string;
				approximateReadingTime: ComputedNumber;
				coverImage: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				resources: Array<never>;
				mediaSources:
					| Array<never>
					| Array<
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'audioRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'pdfLink';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									audioFile: AudioFile;
									hostName: string;
									hostAvatar?: HostAvatar;
									date: string;
									duration: string;
									_type: 'spaceRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'spotifyPodcastEpisode';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									videoId: string;
									_type: 'youTubeVideo';
									_key: string;
							  }
					  >;
				author: {
					_id: string;
					slug: string;
					name: string;
					image: {
						asset?: SanityImageAssetReference;
						media?: unknown;
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					};
					nationality: {
						_id: string;
						_type: 'nationality';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						country: string;
						flag: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						};
					};
					bornOn: string | null;
					bornOnYear: ComputedNumber | null;
					diedOn: string | null;
					diedOnYear: ComputedNumber | null;
					resources: Array<never>;
				};
		  }>
		| Array<never>;
} | null;

// Source: ../src/api/_queries/contributor.query.ts
// Variable: allContributorsQuery
// Query: *[_type == 'contributor' && !(_id in path('drafts.**'))]{	name,	'slug': slug.current,	area,	link {		handle,		url	},	notes}|order(name asc)
export type AllContributorsQueryResult = Array<{
	name: string;
	slug: string;
	area: 'content-generation' | 'content-pick' | 'programming' | 'staff';
	link: {
		handle: string | null;
		url: string | null;
	} | null;
	notes: string | null;
}>;

// Source: ../src/api/_queries/literary-work.query.ts
// Variable: literaryWorkBySlugQuery
// Query: *[_type == 'literaryWork' && slug.current == $slug && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,    coverImage,    editorialNote,    'badLanguage': coalesce(badLanguage, false),    'originalPublication': coalesce(originalPublication, ''),    'publishedAt': coalesce(publishedAt, _createdAt),    totalReadingTime,    'sectionCount': count(content),    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'mediaSources': coalesce(mediaSources[]{        ...,        _type == 'spaceRecording' => {            'audioUrl': audioFile.asset->url        }    }, []),    'resources': coalesce(resources[]{        title,        url,        resourceType->{            'slug': slug.current,            title,            description        }    }, []),    'authors': coalesce(authors[]-> {        _id,        'slug': slug.current,        name,        image,        nationality->,        biography,        bornOn,        bornOnYear,        diedOn,        diedOnYear,        'resources': coalesce(resources[]{            title,            url,            resourceType->{                'slug': slug.current,                title,                description            }        }, []),        'tags': []    }, []),    'content': coalesce(content[]{        _key,        title,        'epigraphs': coalesce(epigraphs[]{ text, reference }, []),        body,        readingTime    }, [])}[0]
export type LiteraryWorkBySlugQueryResult = {
	_id: string;
	slug: string;
	title: string;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	editorialNote: Markdown | null;
	badLanguage: boolean | false;
	originalPublication: string | '';
	publishedAt: string;
	totalReadingTime: number | null;
	sectionCount: number;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources:
		| Array<{
				title: string;
				url: string;
				resourceType: {
					slug: string;
					title: string;
					description: string;
				};
		  }>
		| Array<never>;
	authors: Array<{
		_id: string;
		slug: string;
		name: string;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		nationality: {
			_id: string;
			_type: 'nationality';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			country: string;
			flag: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		biography: Markdown;
		bornOn: string | null;
		bornOnYear: ComputedNumber | null;
		diedOn: string | null;
		diedOnYear: ComputedNumber | null;
		resources:
			| Array<{
					title: string;
					url: string;
					resourceType: {
						slug: string;
						title: string;
						description: string;
					};
			  }>
			| Array<never>;
		tags: Array<never>;
	}>;
	content: Array<{
		_key: string;
		title: string | null;
		epigraphs:
			| Array<{
					text: Markdown | null;
					reference: Markdown | null;
			  }>
			| Array<never>;
		body: Markdown;
		readingTime: number | null;
	}>;
} | null;

// Source: ../src/api/_queries/literary-work.query.ts
// Variable: literaryWorkSectionBySlugQuery
// Query: *[_type == 'literaryWork' && slug.current == $slug && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,    coverImage,    editorialNote,    'badLanguage': coalesce(badLanguage, false),    'originalPublication': coalesce(originalPublication, ''),    'publishedAt': coalesce(publishedAt, _createdAt),    totalReadingTime,    'sectionCount': count(content),    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'mediaSources': coalesce(mediaSources[]{        ...,        _type == 'spaceRecording' => {            'audioUrl': audioFile.asset->url        }    }, []),    'resources': coalesce(resources[]{        title,        url,        resourceType->{            'slug': slug.current,            title,            description        }    }, []),    'authors': coalesce(authors[]-> {        _id,        'slug': slug.current,        name,        image,        nationality->,        biography,        bornOn,        bornOnYear,        diedOn,        diedOnYear,        'resources': coalesce(resources[]{            title,            url,            resourceType->{                'slug': slug.current,                title,                description            }        }, []),        'tags': []    }, []),    'section': content[$section...$sectionEnd]{        _key,        title,        'epigraphs': coalesce(epigraphs[]{ text, reference }, []),        body,        readingTime    }}[0]
export type LiteraryWorkSectionBySlugQueryResult = {
	_id: string;
	slug: string;
	title: string;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	editorialNote: Markdown | null;
	badLanguage: boolean | false;
	originalPublication: string | '';
	publishedAt: string;
	totalReadingTime: number | null;
	sectionCount: number;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources:
		| Array<{
				title: string;
				url: string;
				resourceType: {
					slug: string;
					title: string;
					description: string;
				};
		  }>
		| Array<never>;
	authors: Array<{
		_id: string;
		slug: string;
		name: string;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		nationality: {
			_id: string;
			_type: 'nationality';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			country: string;
			flag: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		biography: Markdown;
		bornOn: string | null;
		bornOnYear: ComputedNumber | null;
		diedOn: string | null;
		diedOnYear: ComputedNumber | null;
		resources:
			| Array<{
					title: string;
					url: string;
					resourceType: {
						slug: string;
						title: string;
						description: string;
					};
			  }>
			| Array<never>;
		tags: Array<never>;
	}>;
	section: Array<{
		_key: string;
		title: string | null;
		epigraphs:
			| Array<{
					text: Markdown | null;
					reference: Markdown | null;
			  }>
			| Array<never>;
		body: Markdown;
		readingTime: number | null;
	}>;
} | null;

// Source: ../src/api/_queries/literary-work.query.ts
// Variable: readingTimeBackfillCandidatesQuery
// Query: *[_type == 'literaryWork' && !(_id in path('drafts.**')) && _id > $cursor  && (!defined(totalReadingTime) || count(content[!defined(readingTime)]) > 0)]| order(_id asc) [0...$pageSize] {    _id,    'slug': slug.current,    totalReadingTime,    'content': coalesce(content[]{ _key, body, readingTime }, [])}
export type ReadingTimeBackfillCandidatesQueryResult = Array<{
	_id: string;
	slug: string;
	totalReadingTime: number | null;
	content: Array<{
		_key: string;
		body: Markdown;
		readingTime: number | null;
	}>;
}>;

// Source: ../src/api/_queries/sitemap.query.ts
// Variable: sitemapSlugsQuery
// Query: {	"stories": *[_type == "story" && !(_id in path('drafts.**'))]{ "slug": slug.current, "lastmod": coalesce(publishedAt, _createdAt) },	"authors": *[_type == "author" && !(_id in path('drafts.**'))]{ "slug": slug.current, "lastmod": _createdAt },	"storylists": *[_type == "storylist" && !(_id in path('drafts.**'))]{ "slug": slug.current, "lastmod": _createdAt }}
export type SitemapSlugsQueryResult = {
	stories: Array<{
		slug: string;
		lastmod: string;
	}>;
	authors: Array<{
		slug: string;
		lastmod: string;
	}>;
	storylists: Array<{
		slug: string;
		lastmod: string;
	}>;
};

// Source: ../src/api/_queries/story.query.ts
// Variable: storiesByAuthorSlugQuery
// Query: *[_type == 'story' && author->slug.current == $slug && !(_id in path('drafts.**'))][$start...$end]{    _id,    'slug': slug.current,    title,    'badLanguage': coalesce(badLanguage, false),    'body': coalesce(body[0...3], []),    'originalPublication': coalesce(originalPublication, ''),    approximateReadingTime,    coverImage,    'mediaSources': coalesce(mediaSources[], []),    'resources': coalesce(resources[]{        title,        url,        resourceType->{            'slug': slug.current,            title,            description        }    }, []),}|order(title asc)
export type StoriesByAuthorSlugQueryResult = Array<{
	_id: string;
	slug: string;
	title: string;
	badLanguage: boolean;
	body:
		| Array<never>
		| Array<
				| {
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: 'span';
							_key: string;
						}>;
						style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
						listItem?: 'bullet' | 'number';
						markDefs?: Array<{
							href?: string;
							_type: 'link';
							_key: string;
						}>;
						level?: number;
						_type: 'block';
						_key: string;
				  }
				| {
						asset?: SanityImageAssetReference;
						media?: unknown;
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
						_key: string;
				  }
		  >;
	originalPublication: string;
	approximateReadingTime: ComputedNumber;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources:
		| Array<{
				title: string;
				url: string;
				resourceType: {
					slug: string;
					title: string;
					description: string;
				};
		  }>
		| Array<never>;
}>;

// Source: ../src/api/_queries/story.query.ts
// Variable: storyBySlugQuery
// Query: *[_type == 'story' && slug.current == $slug && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,     'badLanguage': coalesce(badLanguage, false),    'epigraphs': coalesce(epigraphs[]{        text,        'reference': coalesce(reference[], [])    }, []),    'body': coalesce(body, []),    'review': coalesce(review, []),    'originalPublication': coalesce(originalPublication, ''),    'publishedAt': coalesce(publishedAt, _createdAt),    'updatedAt': _updatedAt,    approximateReadingTime,    coverImage,    'mediaSources': coalesce(mediaSources[]{        ...,        _type == 'spaceRecording' => {            'audioUrl': audioFile.asset->url        }    }, []),    'resources': coalesce(resources[]{        title,        url,        resourceType->{            'slug': slug.current,            title,            description        }    }, []),    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'author': author-> {        _id,        'slug': slug.current,        name,        image,        nationality->,        biography,        bornOn,        bornOnYear,        diedOn,        diedOnYear,        'resources': coalesce(resources[]{            title,            url,            resourceType->{                'slug': slug.current,                title,                description            }        }, []),        'tags': []    }}[0]
export type StoryBySlugQueryResult = {
	_id: string;
	slug: string;
	title: string;
	badLanguage: boolean;
	epigraphs:
		| Array<{
				text: BlockContent;
				reference:
					| Array<never>
					| Array<
							| {
									children?: Array<{
										marks?: Array<string>;
										text?: string;
										_type: 'span';
										_key: string;
									}>;
									style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
									listItem?: 'bullet' | 'number';
									markDefs?: Array<{
										href?: string;
										_type: 'link';
										_key: string;
									}>;
									level?: number;
									_type: 'block';
									_key: string;
							  }
							| {
									asset?: SanityImageAssetReference;
									media?: unknown;
									hotspot?: SanityImageHotspot;
									crop?: SanityImageCrop;
									_type: 'image';
									_key: string;
							  }
					  >;
		  }>
		| Array<never>;
	body: Array<never> | BlockContent;
	review: Array<never> | BlockContent;
	originalPublication: string;
	publishedAt: string;
	updatedAt: string;
	approximateReadingTime: ComputedNumber;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources:
		| Array<{
				title: string;
				url: string;
				resourceType: {
					slug: string;
					title: string;
					description: string;
				};
		  }>
		| Array<never>;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	author: {
		_id: string;
		slug: string;
		name: string;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		nationality: {
			_id: string;
			_type: 'nationality';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			country: string;
			flag: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		biography: Markdown;
		bornOn: string | null;
		bornOnYear: ComputedNumber | null;
		diedOn: string | null;
		diedOnYear: ComputedNumber | null;
		resources:
			| Array<{
					title: string;
					url: string;
					resourceType: {
						slug: string;
						title: string;
						description: string;
					};
			  }>
			| Array<never>;
		tags: Array<never>;
	};
} | null;

// Source: ../src/api/_queries/story.query.ts
// Variable: storiesBySlugsQuery
// Query: *[_type == 'story' && slug.current in $slugs && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,    'badLanguage': coalesce(badLanguage, false),    'epigraphs': [],    'body': [],    'review': [],    'originalPublication': coalesce(originalPublication, ''),    approximateReadingTime,    coverImage,    'mediaSources': coalesce(mediaSources[], []),    'resources': [],    'author': author-> {        _id,        'slug': slug.current,        name,        image,        nationality->,        bornOn,        bornOnYear,        diedOn,        diedOnYear,        'resources': []    }}
export type StoriesBySlugsQueryResult = Array<{
	_id: string;
	slug: string;
	title: string;
	badLanguage: boolean;
	epigraphs: Array<never>;
	body: Array<never>;
	review: Array<never>;
	originalPublication: string;
	approximateReadingTime: ComputedNumber;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources: Array<never>;
	author: {
		_id: string;
		slug: string;
		name: string;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		nationality: {
			_id: string;
			_type: 'nationality';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			country: string;
			flag: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		bornOn: string | null;
		bornOnYear: ComputedNumber | null;
		diedOn: string | null;
		diedOnYear: ComputedNumber | null;
		resources: Array<never>;
	};
}>;

// Source: ../src/api/_queries/story.query.ts
// Variable: allStoriesQuery
// Query: *[_type == 'story' && !(_id in path('drafts.**'))][$start...$end]{    _id,    'slug': slug.current,    title,    'badLanguage': coalesce(badLanguage, false),    'body': [],    'review': [],    'originalPublication': coalesce(originalPublication, ''),    approximateReadingTime,    coverImage,    'mediaSources': coalesce(mediaSources[], []),    'resources': [],    'author': author-> {        _id,        'slug': slug.current,        name,        image,        nationality->,        bornOn,        bornOnYear,        diedOn,        diedOnYear,        'resources': []    }}|order(title asc)
export type AllStoriesQueryResult = Array<{
	_id: string;
	slug: string;
	title: string;
	badLanguage: boolean;
	body: Array<never>;
	review: Array<never>;
	originalPublication: string;
	approximateReadingTime: ComputedNumber;
	coverImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
	resources: Array<never>;
	author: {
		_id: string;
		slug: string;
		name: string;
		image: {
			asset?: SanityImageAssetReference;
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			_type: 'image';
		};
		nationality: {
			_id: string;
			_type: 'nationality';
			_createdAt: string;
			_updatedAt: string;
			_rev: string;
			country: string;
			flag: {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
			};
		};
		bornOn: string | null;
		bornOnYear: ComputedNumber | null;
		diedOn: string | null;
		diedOnYear: ComputedNumber | null;
		resources: Array<never>;
	};
}>;

// Source: ../src/api/_queries/storylist.query.ts
// Variable: storylistTeasersQuery
// Query: *[_type == 'storylist' && !(_id in path('drafts.**'))]{    _id,    'slug': slug.current,    title,    description,    featuredImage,    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'storyCoverImages': coalesce(stories[]->coverImage, []),    'count': coalesce(count(stories), 0),    config,    'tabs': [],		'mediaSources': coalesce(mediaSources[], []),    }
export type StorylistTeasersQueryResult = Array<{
	_id: string;
	slug: string;
	title: string;
	description: BlockContent;
	featuredImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	storyCoverImages:
		| Array<{
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
		  }>
		| Array<never>;
	count: number | 0;
	config: {
		showAuthors?: boolean;
	} | null;
	tabs: Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
}>;

// Source: ../src/api/_queries/storylist.query.ts
// Variable: storylistQuery
// Query: *[_type == 'storylist' && slug.current == $slug && !(_id in path('drafts.**'))][0]{    _id,    'slug': slug.current,    title,    description,    featuredImage,    'storyCoverImages': coalesce(stories[0...3]->coverImage, []),    'tags': coalesce(tags[] -> {        title,        'slug': slug.current,        description    }, []),    'stories': coalesce(stories[]->{        _id,        'slug': slug.current,        title,        'badLanguage': coalesce(badLanguage, false),        'body': coalesce(body[0...3], []),        'originalPublication': coalesce(originalPublication, ''),        approximateReadingTime,        coverImage,        'resources': [],        'mediaSources': coalesce(mediaSources[], []),        'author': author->{            _id,            'slug': slug.current,            name,            image,            nationality->,						bornOn,						bornOnYear,						diedOn,						diedOnYear,            'resources': [],        }    }, []),    'count': coalesce(count(stories), 0),    config,    'tabs': coalesce(tabs[], []),		'mediaSources': coalesce(mediaSources[]{			...,			_type == 'spaceRecording' => {				'audioUrl': audioFile.asset->url			}		}, []),    }
export type StorylistQueryResult = {
	_id: string;
	slug: string;
	title: string;
	description: BlockContent;
	featuredImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	storyCoverImages:
		| Array<{
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: 'image';
		  }>
		| Array<never>;
	tags:
		| Array<{
				title: string;
				slug: string;
				description: string;
		  }>
		| Array<never>;
	stories:
		| Array<{
				_id: string;
				slug: string;
				title: string;
				badLanguage: boolean;
				body:
					| Array<never>
					| Array<
							| {
									children?: Array<{
										marks?: Array<string>;
										text?: string;
										_type: 'span';
										_key: string;
									}>;
									style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
									listItem?: 'bullet' | 'number';
									markDefs?: Array<{
										href?: string;
										_type: 'link';
										_key: string;
									}>;
									level?: number;
									_type: 'block';
									_key: string;
							  }
							| {
									asset?: SanityImageAssetReference;
									media?: unknown;
									hotspot?: SanityImageHotspot;
									crop?: SanityImageCrop;
									_type: 'image';
									_key: string;
							  }
					  >;
				originalPublication: string;
				approximateReadingTime: ComputedNumber;
				coverImage: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				resources: Array<never>;
				mediaSources:
					| Array<never>
					| Array<
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'audioRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'pdfLink';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									audioFile: AudioFile;
									hostName: string;
									hostAvatar?: HostAvatar;
									date: string;
									duration: string;
									_type: 'spaceRecording';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									url: string;
									_type: 'spotifyPodcastEpisode';
									_key: string;
							  }
							| {
									title: string;
									description: Markdown;
									videoId: string;
									_type: 'youTubeVideo';
									_key: string;
							  }
					  >;
				author: {
					_id: string;
					slug: string;
					name: string;
					image: {
						asset?: SanityImageAssetReference;
						media?: unknown;
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					};
					nationality: {
						_id: string;
						_type: 'nationality';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						country: string;
						flag: {
							asset?: SanityImageAssetReference;
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						};
					};
					bornOn: string | null;
					bornOnYear: ComputedNumber | null;
					diedOn: string | null;
					diedOnYear: ComputedNumber | null;
					resources: Array<never>;
				};
		  }>
		| Array<never>;
	count: number | 0;
	config: {
		showAuthors?: boolean;
	} | null;
	tabs:
		| Array<{
				title: string;
				slug: Slug;
				content: BlockContent;
				icon?: string;
				_type: 'storylistTab';
				_key: string;
		  }>
		| Array<never>;
	mediaSources:
		| Array<never>
		| Array<
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'audioRecording';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'pdfLink';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						audioFile: AudioFile;
						hostName: string;
						hostAvatar?: HostAvatar;
						date: string;
						duration: string;
						_type: 'spaceRecording';
						_key: string;
						audioUrl: string | null;
				  }
				| {
						title: string;
						description: Markdown;
						url: string;
						_type: 'spotifyPodcastEpisode';
						_key: string;
				  }
				| {
						title: string;
						description: Markdown;
						videoId: string;
						_type: 'youTubeVideo';
						_key: string;
				  }
		  >;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		"\n*[_type == 'author' && slug.current == $slug && !(_id in path('drafts.**'))][0]\n{\n    _id,\n    'slug': slug.current,\n    'createdAt': _createdAt,\n    'updatedAt': _updatedAt,\n    name,\n    image,\n    nationality->,\n    biography,\n    bornOn,\n\t\tbornOnYear,\n    diedOn,\n\t\tdiedOnYear,\n    'resources': coalesce(resources[]{\n        title,\n        url,\n        resourceType->{\n        \t'slug': slug.current,\n        \ttitle,\n        \tdescription\n        }\n    }, []),\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, [])\n}": AuthorBySlugQueryResult;
		"\n*[_type == 'author' && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    name,\n    image,\n    nationality->,\n    bornOn,\n \t\tbornOnYear,\n    diedOn,\n    diedOnYear,\n    'resources': []\n}|order(name asc)": AuthorsQueryResult;
		"\n*[_type == 'collection' && slug.current == $slug && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    description,\n    featuredImage,\n    'config': { 'showAuthors': coalesce(config.showAuthors, false) },\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'mediaSources': coalesce(mediaSources[]{\n        ...,\n        _type == 'spaceRecording' => {\n            'audioUrl': audioFile.asset->url\n        }\n    }, []),\n    'literaryWorks': coalesce(literaryWorks[]->{\n        _id,\n        'slug': slug.current,\n        title,\n        coverImage,\n        totalReadingTime,\n        'sectionCount': count(content),\n        'tags': coalesce(tags[] -> {\n            title,\n            'slug': slug.current,\n            description\n        }, []),\n        'mediaSources': coalesce(mediaSources[]{\n            ...,\n            _type == 'spaceRecording' => {\n                'audioUrl': audioFile.asset->url\n            }\n        }, []),\n        'authors': coalesce(authors[]->{\n            _id,\n            'slug': slug.current,\n            name,\n            image,\n            nationality->,\n            bornOn,\n            bornOnYear,\n            diedOn,\n            diedOnYear\n        }, []),\n        'teaserSection': content[0...1]{\n            _key,\n            title,\n            body,\n            readingTime\n        }\n    }, [])\n}[0]": CollectionBySlugQueryResult;
		"\n*[_type == 'collection' && !(_id in path('drafts.**'))]\n| order(title asc)\n{\n    _id,\n    'slug': slug.current,\n    title,\n    description,\n    featuredImage,\n    'config': { 'showAuthors': coalesce(config.showAuthors, false) },\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'mediaSources': coalesce(mediaSources[]{\n        ...,\n        _type == 'spaceRecording' => {\n            'audioUrl': audioFile.asset->url\n        }\n    }, []),\n    'count': coalesce(count(literaryWorks), 0),\n    'literaryWorkCoverImages': coalesce(literaryWorks[0...3]->coverImage, [])\n}": CollectionsQueryResult;
		"\n*[_type == 'rotatingContent' && _id == 'rotatingContent'][0]{\n    _id,\n    name,\n    'mostRead': coalesce(mostRead[]->{\n        _id,\n        'slug': slug.current,\n        title,\n        'badLanguage': coalesce(badLanguage, false),\n        'body': [],\n        'originalPublication': coalesce(originalPublication, ''),\n        approximateReadingTime,\n        coverImage,\n        'resources': [],\n        'mediaSources': coalesce(mediaSources[], []),\n        'author': author-> {\n            _id,\n            'slug': slug.current,\n            name,\n            image,\n            nationality->,\n\t\t\t\t\t\tbornOn,\n\t\t\t\t\t\tbornOnYear,\n\t\t\t\t\t\tdiedOn,\n\t\t\t\t\t\tdiedOnYear,\n            'resources': [],\n        }\n    },[])\n}": RotatingContentQueryResult;
		"\n*[_type == 'landingPage' && !(_id in path('drafts.**')) && slug.current in $slugs]{\n\t\t_id,\n\t\t'slug': slug.current,\n\t\tconfig,\n}": LandingPageListQueryResult;
		"\n*[_type == 'landingPage' && !(_id in path('drafts.**')) && config <= $currentSlug]{\n    _id,\n    _type,\n    'slug': slug.current,\n    config,\n    'cards': coalesce(cards[],[]),\n    'campaigns': coalesce(campaigns[],[]),\n    'latestReads': coalesce(latestReads,[]),\n} | order(config desc, _createdAt desc)[0]\n": LatestLandingPageReferencesQueryResult;
		"\n*[_type == 'landingPage' && !(_id in path('drafts.**')) && slug.current == $slug][0]{\n    _id,\n    'slug': slug.current,\n    config,\n    'cards': coalesce(cards[]->{\n        _id,\n        title,\n        'slug': slug.current,\n        description,\n        featuredImage,\n        'tags': coalesce(tags[] -> {\n            title,\n            'slug': slug.current,\n            description\n        }, []),\n        'storyCoverImages': coalesce(stories[]->coverImage, []),\n        'count': coalesce(count(stories), 0),\n\t\t\t\tconfig,\n\t\t\t\t'tabs': [],\n\t      'mediaSources': coalesce(mediaSources[], []),\n    },[]),\n    'campaigns': coalesce(campaigns[]->{\n        _id,\n        'title': coalesce(title, ''),\n        'slug': coalesce(slug.current, ''),\n        'url': coalesce(url, ''),\n        'contents': {\n            'xs': {\n                'image': contents.xs.image\n            },\n            'md': {\n                'image': contents.md.image\n            }\n        }\n    },[]),\n    'latestReads': coalesce(latestReads[]->{\n        _id,\n        'slug': slug.current,\n        title,\n        'badLanguage': coalesce(badLanguage, false),\n        'body': [],\n        'originalPublication': coalesce(originalPublication, ''),\n        approximateReadingTime,\n        coverImage,\n        'resources': [],\n        'mediaSources': coalesce(mediaSources[], []),\n        'author': author-> { \n            _id,\n            'slug': slug.current,\n            name,\n            image,\n            nationality->,\n\t\t\t\t\t\tbornOn,\n\t\t\t\t\t\tbornOnYear,\n\t\t\t\t\t\tdiedOn,\n\t\t\t\t\t\tdiedOnYear,\n            'resources': [],\n        }\n    },[]),\n}": LandingPageContentQueryResult;
		"\n*[_type == 'contributor' && !(_id in path('drafts.**'))]\n{\n\tname,\n\t'slug': slug.current,\n\tarea,\n\tlink {\n\t\thandle,\n\t\turl\n\t},\n\tnotes\n}|order(name asc)\n": AllContributorsQueryResult;
		"\n*[_type == 'literaryWork' && slug.current == $slug && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    coverImage,\n    editorialNote,\n    'badLanguage': coalesce(badLanguage, false),\n    'originalPublication': coalesce(originalPublication, ''),\n    'publishedAt': coalesce(publishedAt, _createdAt),\n    totalReadingTime,\n    'sectionCount': count(content),\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'mediaSources': coalesce(mediaSources[]{\n        ...,\n        _type == 'spaceRecording' => {\n            'audioUrl': audioFile.asset->url\n        }\n    }, []),\n    'resources': coalesce(resources[]{\n        title,\n        url,\n        resourceType->{\n            'slug': slug.current,\n            title,\n            description\n        }\n    }, []),\n    'authors': coalesce(authors[]-> {\n        _id,\n        'slug': slug.current,\n        name,\n        image,\n        nationality->,\n        biography,\n        bornOn,\n        bornOnYear,\n        diedOn,\n        diedOnYear,\n        'resources': coalesce(resources[]{\n            title,\n            url,\n            resourceType->{\n                'slug': slug.current,\n                title,\n                description\n            }\n        }, []),\n        'tags': []\n    }, []),\n    'content': coalesce(content[]{\n        _key,\n        title,\n        'epigraphs': coalesce(epigraphs[]{ text, reference }, []),\n        body,\n        readingTime\n    }, [])\n}[0]": LiteraryWorkBySlugQueryResult;
		"\n*[_type == 'literaryWork' && slug.current == $slug && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    coverImage,\n    editorialNote,\n    'badLanguage': coalesce(badLanguage, false),\n    'originalPublication': coalesce(originalPublication, ''),\n    'publishedAt': coalesce(publishedAt, _createdAt),\n    totalReadingTime,\n    'sectionCount': count(content),\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'mediaSources': coalesce(mediaSources[]{\n        ...,\n        _type == 'spaceRecording' => {\n            'audioUrl': audioFile.asset->url\n        }\n    }, []),\n    'resources': coalesce(resources[]{\n        title,\n        url,\n        resourceType->{\n            'slug': slug.current,\n            title,\n            description\n        }\n    }, []),\n    'authors': coalesce(authors[]-> {\n        _id,\n        'slug': slug.current,\n        name,\n        image,\n        nationality->,\n        biography,\n        bornOn,\n        bornOnYear,\n        diedOn,\n        diedOnYear,\n        'resources': coalesce(resources[]{\n            title,\n            url,\n            resourceType->{\n                'slug': slug.current,\n                title,\n                description\n            }\n        }, []),\n        'tags': []\n    }, []),\n    'section': content[$section...$sectionEnd]{\n        _key,\n        title,\n        'epigraphs': coalesce(epigraphs[]{ text, reference }, []),\n        body,\n        readingTime\n    }\n}[0]": LiteraryWorkSectionBySlugQueryResult;
		"\n*[_type == 'literaryWork' && !(_id in path('drafts.**')) && _id > $cursor\n  && (!defined(totalReadingTime) || count(content[!defined(readingTime)]) > 0)]\n| order(_id asc) [0...$pageSize] {\n    _id,\n    'slug': slug.current,\n    totalReadingTime,\n    'content': coalesce(content[]{ _key, body, readingTime }, [])\n}": ReadingTimeBackfillCandidatesQueryResult;
		'{\n\t"stories": *[_type == "story" && !(_id in path(\'drafts.**\'))]{ "slug": slug.current, "lastmod": coalesce(publishedAt, _createdAt) },\n\t"authors": *[_type == "author" && !(_id in path(\'drafts.**\'))]{ "slug": slug.current, "lastmod": _createdAt },\n\t"storylists": *[_type == "storylist" && !(_id in path(\'drafts.**\'))]{ "slug": slug.current, "lastmod": _createdAt }\n}': SitemapSlugsQueryResult;
		"\n*[_type == 'story' && author->slug.current == $slug && !(_id in path('drafts.**'))][$start...$end]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    'badLanguage': coalesce(badLanguage, false),\n    'body': coalesce(body[0...3], []),\n    'originalPublication': coalesce(originalPublication, ''),\n    approximateReadingTime,\n    coverImage,\n    'mediaSources': coalesce(mediaSources[], []),\n    'resources': coalesce(resources[]{\n        title,\n        url,\n        resourceType->{\n            'slug': slug.current,\n            title,\n            description\n        }\n    }, []),\n}|order(title asc)": StoriesByAuthorSlugQueryResult;
		"\n*[_type == 'story' && slug.current == $slug && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    title, \n    'badLanguage': coalesce(badLanguage, false),\n    'epigraphs': coalesce(epigraphs[]{\n        text,\n        'reference': coalesce(reference[], [])\n    }, []),\n    'body': coalesce(body, []),\n    'review': coalesce(review, []),\n    'originalPublication': coalesce(originalPublication, ''),\n    'publishedAt': coalesce(publishedAt, _createdAt),\n    'updatedAt': _updatedAt,\n    approximateReadingTime,\n    coverImage,\n    'mediaSources': coalesce(mediaSources[]{\n        ...,\n        _type == 'spaceRecording' => {\n            'audioUrl': audioFile.asset->url\n        }\n    }, []),\n    'resources': coalesce(resources[]{\n        title,\n        url,\n        resourceType->{\n            'slug': slug.current,\n            title,\n            description\n        }\n    }, []),\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'author': author-> {\n        _id,\n        'slug': slug.current,\n        name,\n        image,\n        nationality->,\n        biography,\n        bornOn,\n        bornOnYear,\n        diedOn,\n        diedOnYear,\n        'resources': coalesce(resources[]{\n            title,\n            url,\n            resourceType->{\n                'slug': slug.current,\n                title,\n                description\n            }\n        }, []),\n        'tags': []\n    }\n}[0]": StoryBySlugQueryResult;
		"\n*[_type == 'story' && slug.current in $slugs && !(_id in path('drafts.**'))]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    'badLanguage': coalesce(badLanguage, false),\n    'epigraphs': [],\n    'body': [],\n    'review': [],\n    'originalPublication': coalesce(originalPublication, ''),\n    approximateReadingTime,\n    coverImage,\n    'mediaSources': coalesce(mediaSources[], []),\n    'resources': [],\n    'author': author-> {\n        _id,\n        'slug': slug.current,\n        name,\n        image,\n        nationality->,\n        bornOn,\n        bornOnYear,\n        diedOn,\n        diedOnYear,\n        'resources': []\n    }\n}": StoriesBySlugsQueryResult;
		"\n*[_type == 'story' && !(_id in path('drafts.**'))]\n[$start...$end]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    'badLanguage': coalesce(badLanguage, false),\n    'body': [],\n    'review': [],\n    'originalPublication': coalesce(originalPublication, ''),\n    approximateReadingTime,\n    coverImage,\n    'mediaSources': coalesce(mediaSources[], []),\n    'resources': [],\n    'author': author-> {\n        _id,\n        'slug': slug.current,\n        name,\n        image,\n        nationality->,\n        bornOn,\n        bornOnYear,\n        diedOn,\n        diedOnYear,\n        'resources': []\n    }\n}|order(title asc)": AllStoriesQueryResult;
		"\n*[_type == 'storylist' && !(_id in path('drafts.**'))]{\n    _id,\n    'slug': slug.current,\n    title,\n    description,\n    featuredImage,\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'storyCoverImages': coalesce(stories[]->coverImage, []),\n    'count': coalesce(count(stories), 0),\n    config,\n    'tabs': [],\n\t\t'mediaSources': coalesce(mediaSources[], []),\n    }\n": StorylistTeasersQueryResult;
		"\n*[_type == 'storylist' && slug.current == $slug && !(_id in path('drafts.**'))][0]\n{\n    _id,\n    'slug': slug.current,\n    title,\n    description,\n    featuredImage,\n    'storyCoverImages': coalesce(stories[0...3]->coverImage, []),\n    'tags': coalesce(tags[] -> {\n        title,\n        'slug': slug.current,\n        description\n    }, []),\n    'stories': coalesce(stories[]->{\n        _id,\n        'slug': slug.current,\n        title,\n        'badLanguage': coalesce(badLanguage, false),\n        'body': coalesce(body[0...3], []),\n        'originalPublication': coalesce(originalPublication, ''),\n        approximateReadingTime,\n        coverImage,\n        'resources': [],\n        'mediaSources': coalesce(mediaSources[], []),\n        'author': author->{\n            _id,\n            'slug': slug.current,\n            name,\n            image,\n            nationality->,\n\t\t\t\t\t\tbornOn,\n\t\t\t\t\t\tbornOnYear,\n\t\t\t\t\t\tdiedOn,\n\t\t\t\t\t\tdiedOnYear,\n            'resources': [],\n        }\n    }, []),\n    'count': coalesce(count(stories), 0),\n    config,\n    'tabs': coalesce(tabs[], []),\n\t\t'mediaSources': coalesce(mediaSources[]{\n\t\t\t...,\n\t\t\t_type == 'spaceRecording' => {\n\t\t\t\t'audioUrl': audioFile.asset->url\n\t\t\t}\n\t\t}, []),\n    }\n": StorylistQueryResult;
	}
}
