name: CI

on:
  pull_request:

jobs:
  setup:
    name: 'Setup and dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Select pnpm as package manager
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.12.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Generate testing environment file
        run: pnpm run config

      - name: Rebuild and prepare
        run: pnpm rebuild && pnpm run prepare --if-present

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.12.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Tests
        run: npx nx test --skip-nx-cache

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Select pnpm as package manager
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.12.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run Linter
        run: npx nx lint --skip-nx-cache

  stylelint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.12.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Run stylelint
        run: npx nx stylelint cuentoneta --skip-nx-cache

  e2e:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.12.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npx nx run cuentoneta:e2e-ci --skip-nx-cache

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dist/.playwright/playwright-report/
          retention-days: 7
