name: End-to-end Testing CI

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.15.9

      - name: Use Node.js 22.12
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.12
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate testing environment file
        run: pnpm run config

      - name: Run Tests
        run: npx nx run cuentoneta:e2e-ci --skip-nx-cache

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dist/.playwright/playwright-report/
          retention-days: 7
